// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDWDQK-b21QcX1SNDZw9ZJ5_y__yHvuEwk',
    appId: '1:405369884153:web:af8627835c7f39bf4ac128',
    messagingSenderId: '405369884153',
    projectId: 'fregov-app',
    authDomain: 'fregov-app.firebaseapp.com',
    storageBucket: 'fregov-app.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyATuX1EGl02aKqYNgokoReqQZ2EbnSIyY8',
    appId: '1:405369884153:android:3bc7a742ffb74d8b4ac128',
    messagingSenderId: '405369884153',
    projectId: 'fregov-app',
    storageBucket: 'fregov-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBulFIlYYqmDAbKpR1Pe6W4fY9ZyQpK6IY',
    appId: '1:405369884153:ios:6ad2fba1b3bb15654ac128',
    messagingSenderId: '405369884153',
    projectId: 'fregov-app',
    storageBucket: 'fregov-app.appspot.com',
    iosClientId: '405369884153-7jd5pg1l1a7rjr8p1gvtsjd9t7hi5hml.apps.googleusercontent.com',
    iosBundleId: 'com.fregov.fregovApp',
  );
}
